# Generated by Django 6.0.1 on 2026-01-20 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='location',
        ),
        migrations.AddField(
            model_name='ticket',
            name='building',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='room_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('facilities', 'Facilities'), ('academic', 'Academic'), ('technical', 'Technical'), ('administrative', 'Administrative'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterModelTable(
            name='ticket',
            table=None,
        ),
    ]
