# Generated by Django 6.0.1 on 2026-02-20 15:28

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar_url_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_file',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.user_avatar_path),
        ),
    ]
