# Generated by Django 6.0.1 on 2026-02-08 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments_comments', to='tickets.ticketcomment'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments_feedback', to='tickets.ticketfeedback'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments_tickets', to='tickets.ticket'),
        ),
    ]
