# Generated by Django 6.0.1 on 2026-02-12 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketattachment_comment_ticketattachment_feedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticketattachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('feedback__isnull', True), ('ticket__isnull', False)), models.Q(('comment__isnull', False), ('feedback__isnull', True), ('ticket__isnull', True)), models.Q(('comment__isnull', True), ('feedback__isnull', False), ('ticket__isnull', True)), _connector='OR'), name='exactly_one_parent'),
        ),
    ]
